
version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: securecapita
      MYSQL_USER: letmein
      MYSQL_PASSWORD: letmein
    ports:
      - "3306:3306"
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"